#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🛠 Running pre-commit checks..."

npm run lint && npm run format
if [ $? -ne 0 ]; then
  echo "❌ Pre-commit checks failed. Fix errors before committing."
  exit 1
fi

echo "✅ All checks passed! Proceeding with commit."
